package edu.pw.eiti.pik.project;

public enum ProjectStatus {
    CREATED,
    WAITING_FOR_STUDENTS,
    STARTED,
    SUSPENDED_MISSING_TEACHER,
    SUSPENDED_MISSING_PARTICIPANTS,
    FINISHED,
    OVERDUE,
    SUSPENDED_REPORTED,
    CANCELED,
}
